<?php

// BEGIN Host Settings

/**
 * 
 *      ###########################################################
 *      #                                                         #
 *      #        NOTICE: Read before modifying this file or       #
 *      #           your changes could be overwritten!            #
 *      #                                                         #
 *      ###########################################################
 * 
 *      The 'Host Settings' block is managed by the host.
 *      
 *      The settings here are required for the site to run
 *      properly. Any changes made to this block will be
 *      overwritten. If the block is deleted, it will be
 *      recreated and placed at the beginning of the file.
 * 
 *      Any changes made before or after the block will be
 *      preserved and respected.
 * 
 *      Any changes to the block markers (the lines with
 *     'BEGIN Host Settings' and 'END Host Settings') may
 *      cause the block to be recreated or duplicated.
 * 
 *      If you run into issues and need to reset, delete
 *      the entire file or delete all text inside; the
 *      file will be recreated with this block intact.
 * 
 */

// a helper function to lookup "env_FILE", "env", then fallback
if (!function_exists('getenv_docker')) {
        // https://github.com/docker-library/wordpress/issues/588 (WP-CLI will load this file 2x)
        function getenv_docker($env, $default) {
                if ($fileEnv = getenv($env . '_FILE')) {
                        return rtrim(file_get_contents($fileEnv), "\r\n");
                }
                else if (($val = getenv($env)) !== false) {
                        return $val;
                }
                else {
                        return $default;
                }
        }
}

// Table prefix
$table_prefix = getenv_docker('WORDPRESS_TABLE_PREFIX', 'wp_');

// Site URLs. Only apply if not running in WP-CLI context
$cliEnv = getenv_docker('IS_RUNNING_WP_CLI', '');
if ($cliEnv == '') {
    define( 'WP_HOME', getenv_docker('WORDPRESS_URL', '') );
    define( 'WP_SITEURL', getenv_docker('WORDPRESS_URL', '') );
}

// Cloudflare Variables
define( 'CLOUDFLARE_ZONE_ID ', getenv_docker('CLOUDFLARE_ZONE_ID', '') );
define( 'CLOUDFLARE_API_TOKEN ', getenv_docker('CLOUDFLARE_API_TOKEN', '') );

// SSO Variables
define( 'OIDC_CLIENT_ID', getenv_docker('OIDC_CLIENT_ID', '') );
define( 'OIDC_CLIENT_SECRET', getenv_docker('OIDC_CLIENT_SECRET', '') );
define( 'OIDC_CLIENT_SCOPE', getenv_docker('OIDC_CLIENT_SCOPE', 'openid profile email') );
define( 'OIDC_ENDPOINT_LOGIN_URL', 'https://sso.illiosdigital.com/realms/illiosdigital/protocol/openid-connect/auth' );
define( 'OIDC_ENDPOINT_USERINFO_URL', 'https://sso.illiosdigital.com/realms/illiosdigital/protocol/openid-connect/userinfo' );
define( 'OIDC_ENDPOINT_TOKEN_URL', 'https://sso.illiosdigital.com/realms/illiosdigital/protocol/openid-connect/token' );
define( 'OIDC_ENDPOINT_LOGOUT_URL', 'https://sso.illiosdigital.com/realms/illiosdigital/protocol/openid-connect/logout' );

// Only define OIDC_LOGIN_TYPE if it is set in env; otherwise do not
// set in WP so users can modify this on their own
$oidcLoginType = getenv_docker('OIDC_LOGIN_TYPE', '');
if ($oidcLoginType !== '') {
    define('OIDC_LOGIN_TYPE', $oidcLoginType);
}

// Only define OIDC_ENFORCE_PRIVACY if it is set in env; otherwise do not
// set in WP so users can modify this on their own
$oidcEnforcePrivacy = getenv_docker('OIDC_ENFORCE_PRIVACY', '');
if ($oidcEnforcePrivacy !== '') {
    define('OIDC_ENFORCE_PRIVACY', $oidcEnforcePrivacy);
}

// Resource Limits
@ini_set( 'memory_limit', getenv_docker('MEMORY_LIMIT', '2048M') );
@ini_set( 'max_execution_time', '300' );
@ini_set( 'max_input_time', '300' );

// Database Variables
define( 'DB_NAME', getenv_docker('WORDPRESS_DB_NAME', '') );
define( 'DB_USER', getenv_docker('WORDPRESS_DB_USER', '') );
define( 'DB_PASSWORD', getenv_docker('WORDPRESS_DB_PASSWORD', '') );
define( 'DB_HOST', getenv_docker('WORDPRESS_DB_HOST', 'mysql') );
define( 'DB_CHARSET', getenv_docker('WORDPRESS_DB_CHARSET', 'utf8') );
define( 'DB_COLLATE', getenv_docker('WORDPRESS_DB_COLLATE', '') );

// Authentication Unique Keys and Salts. Auto-generated by host as env vars
define( 'AUTH_KEY',         getenv_docker('WORDPRESS_AUTH_KEY',         '') );
define( 'SECURE_AUTH_KEY',  getenv_docker('WORDPRESS_SECURE_AUTH_KEY',  '') );
define( 'LOGGED_IN_KEY',    getenv_docker('WORDPRESS_LOGGED_IN_KEY',    '') );
define( 'NONCE_KEY',        getenv_docker('WORDPRESS_NONCE_KEY',        '') );
define( 'AUTH_SALT',        getenv_docker('WORDPRESS_AUTH_SALT',        '') );
define( 'SECURE_AUTH_SALT', getenv_docker('WORDPRESS_SECURE_AUTH_SALT', '') );
define( 'LOGGED_IN_SALT',   getenv_docker('WORDPRESS_LOGGED_IN_SALT',   '') );
define( 'NONCE_SALT',       getenv_docker('WORDPRESS_NONCE_SALT',       '') );

// WordPress Debugging Mode. Intentionally inside a conditional so it can be
// overridden later in this file if the env var is not set.
$wpDebugEnabled = !!getenv_docker('WORDPRESS_DEBUG', '');
if ($wpDebugEnabled !== '') {
    define('WP_DEBUG', $wpDebugEnabled);
}

// We are behind a reverse proxy
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && strpos($_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') !== false) {
        $_SERVER['HTTPS'] = 'on';
}

// Allow arbitrary extra config to be set via WORDPRESS_CONFIG_EXTRA env var
if ($configExtra = getenv_docker('WORDPRESS_CONFIG_EXTRA', '')) {
        eval($configExtra);
}

// Absolute path to the WordPress directory.
if ( ! defined( 'ABSPATH' ) ) {
        define( 'ABSPATH', __DIR__ . '/' );
}

// Sets up WordPress vars and included files.
require_once ABSPATH . 'wp-settings.php';

/**
 * 
 *      End of 'Host Settings' block.
 * 
 *      Any changes made below the 'END Host Settings'
 *      line will be preserved.
 * 
 */

// END Host Settings